### ISSUE TITLE
[Impersonation] - please delete asap

### ISSUE THREAD

**Issue by ca333** [Fair-Exchange/safecoin#12]
Delete/modify https://github.com/Fair-Exchange/safecoin/blob/master/code_of_conduct.md and remove any references to Komodoplatform members. We otherwise have to interpret this as impersonisation. Negative feedback will be removed as soon as this is resolved.

**Comment by Fair-Exchange** [comment]
Issue resolved within an hour of reporting.  We just did a significant update.  Of thousands of lines of code, this got missed.   Please also note that I need to go back and edit out the Zcash team as well.    Which I have in there, because your team hasn't edited it yet.   Please look into that, we can all do better. Thank you.
