### ISSUE TITLE
concern over forking an open source project.

### ISSUE THREAD

**Issue by Rick-Bird** [Fair-Exchange/safecoin#5]
fork of [komodo](https://github.com/komodoplatform/komodo) without any informations

**Comment by DrunkenMonky** [comment]
To all the SCAM Screamers:
Please visit
https://bitcointalk.org/index.php?topic=2838370.new#new
It says:
[ANN][SAFE][dPOW][POS Safecoin - Komodo Fork - zCash Privacy Secured by Bitcoin

Can it be more clear????

**Comment by Fair-Exchange** [comment]
Hello Rick,

My understanding is that Komodo is an open source project, which was also forked off of zcash and bitcoin.

Do you have specific concerns about how this fork was done?  Was copyright information or licensing missed somewhere?  If so, please let me know and I will correct it.

Otherwise,  I don't recall Zcash calling Komodo a scan when they forked zksnarks almost immediately after they were released, given that the projects were open source for the betterment of all.

thanks
